# Regresión lineal en Python
## El paquete scikit-learn para regresión lineal y la selección de rasgos

In [2]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR #para hacer el modelo lineal
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("../datasets/ads/Advertising.csv")

In [6]:
feature_cols = ["TV", "Radio", "Newspaper"] # columnas de predicción

In [7]:
X = data[feature_cols] #variables predictoras
Y = data["Sales"] # variables a ser predecidas

In [8]:
estimator = SVR(kernel="linear")
selector = RFE(estimator, 2, step=1) # el 2 es para indicar que queremos 2 variables predictivas
selector = selector.fit(X,Y)

In [10]:
selector.support_ # Para saber qué variables han sido las elegidas a ser predictoras
# en el resultado vemos que serían TV y Radio (feature_cols)

array([ True,  True, False])

Como podemos ver, la selección de variables que hicimos en temas anteriores, era correcta, coinciden los resultados

In [13]:
selector.ranking_ # orden de las variables, las variables seleccionadas siempre aparecen con ranking 1.
# las siguientes aparecerán ordenadas según su significación en el modelo

array([1, 1, 2])

In [14]:
from sklearn.linear_model import LinearRegression

In [20]:
X_pred = X[["TV", "Radio"]] 
#Podemos construir el modelo lineal directamente con las variables que queremos

In [21]:
lm = LinearRegression()
lm.fit(X_pred, Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [22]:
lm.intercept_

2.9210999124051362

In [23]:
lm.coef_

array([0.04575482, 0.18799423])

In [24]:
lm.score(X_pred, Y)

0.8971942610828956